spring.application.name=Student Management


spring.datasource.url = jdbc:postgresql://localhost:5432/studentDB
spring.datasource.username = postgres
spring.datasource.password = 1234

spring.jpa.hibernate.ddl-auto = create
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.format_sql = true

#Database initialization with seed data in data.sql file
spring.jpa.defer-datasource-initialization = true
spring.sql.init.mode = always
spring.sql.init.data-locations = classpath:data.sql


spring.jpa.open-in-view=false